"""Helpers for target fields derived from constants rather than source fields."""

from __future__ import annotations

import re

_NULL_LITERAL_RE = re.compile(r"^(?:null|cast\s*\(\s*null\s+as\s+[\w<>,\s]+\))$", re.I)
_STRING_LITERAL_RE = re.compile(r"^'(?:[^']|'')*'$")
_NUMBER_LITERAL_RE = re.compile(r"^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$")
_BACKTICK_TEXT_RE = re.compile(r"`([^`]+)`")
_NULL_CONSTANT_REASON_RE = re.compile(
    r"(?=.*\bnull\b)(?=.*(?:硬编码|常量|固定值|无来源|无上游|不来自|hard[- ]?coded|constant|no source))",
    re.I,
)
_RUNTIME_CONSTANT_RE = re.compile(
    r"\b(?:current_date|current_timestamp|current_time|date_format|unix_timestamp|from_unixtime)\s*\(",
    re.I,
)
_RUNTIME_DATE_VARIABLE_NAME_RE = re.compile(
    r"^(?:"
    r"DATE|FORMAT_DATE|"
    r"[F]?DATE_(?:SUB|ADD)\d+(?:DAY|MONTH|YEAR)|"
    r"MONTH|FMONTH|LAST_YEAR_MONTH|"
    r"[F]?MONTH_(?:SUB|ADD)\d+MONTH(?:_(?:FIRSTDAY|LASTDAY))?"
    r")$",
    re.I,
)
_SHELL_VARIABLE_EXPRESSION_RE = re.compile(
    r"^(?:\$\{(?P<braced>[A-Za-z_][A-Za-z0-9_]*)\}|\$(?P<plain>[A-Za-z_][A-Za-z0-9_]*)|\{\{\s*(?P<jinja>[A-Za-z_][A-Za-z0-9_]*)\s*\}\})$"
)
_ALIASED_EXPRESSION_RE = re.compile(
    r"^(?P<expr>.+?)\s+as\s+`?[A-Za-z_][A-Za-z0-9_]*`?$",
    re.I | re.S,
)
_CAST_EXPRESSION_RE = re.compile(
    r"^cast\s*\(\s*(?P<expr>.+?)\s+as\s+[\w<>,\s]+\)$",
    re.I | re.S,
)
_PLACEHOLDER_TRANSFORM_TEXT_RE = re.compile(
    r"^\s*(?:同上|同前|同上面|同上一条|same\s+as\s+above|same\s+as\s+previous)\s*[。.]?\s*$",
    re.I,
)


def is_placeholder_transform_text(text: str) -> bool:
    """Return True for placeholder text that must never be written to DataHub."""
    return bool(_PLACEHOLDER_TRANSFORM_TEXT_RE.match(text or ""))


def has_explained_transform(expression: str, explanation: str) -> bool:
    """Return True when a source-less mapping has enough logic to remain explainable."""
    return bool(
        (expression or "").strip()
        and (explanation or "").strip()
        and not is_placeholder_transform_text(expression)
        and not is_placeholder_transform_text(explanation)
    )


def is_runtime_date_variable_name(name: str) -> bool:
    """Return True for scheduler date variables generated by format_date-like jobs."""
    return bool(_RUNTIME_DATE_VARIABLE_NAME_RE.match((name or "").strip()))


def is_runtime_date_variable_expression(expression: str) -> bool:
    """Return True for a pure scheduler date variable expression."""
    cleaned = (expression or "").strip().rstrip(";").strip()
    if not cleaned:
        return False
    if (
        (cleaned.startswith("'") and cleaned.endswith("'"))
        or (cleaned.startswith('"') and cleaned.endswith('"'))
    ) and len(cleaned) >= 2:
        cleaned = cleaned[1:-1].strip()
    alias_match = _ALIASED_EXPRESSION_RE.match(cleaned)
    if alias_match:
        return is_runtime_date_variable_expression(alias_match.group("expr"))
    cast_match = _CAST_EXPRESSION_RE.match(cleaned)
    if cast_match:
        return is_runtime_date_variable_expression(cast_match.group("expr"))
    variable_match = _SHELL_VARIABLE_EXPRESSION_RE.match(cleaned)
    if not variable_match:
        return False
    variable_name = next(
        value for value in variable_match.groupdict().values() if value is not None
    )
    return is_runtime_date_variable_name(variable_name)


def is_constant_transform_expression(expression: str) -> bool:
    """Return True for expressions that need no upstream source field."""
    cleaned = (expression or "").strip().rstrip(";").strip()
    if not cleaned:
        return False
    if is_runtime_date_variable_expression(cleaned):
        return True
    lowered = cleaned.lower()
    if _NULL_LITERAL_RE.match(cleaned):
        return True
    if lowered in {"true", "false"}:
        return True
    if _STRING_LITERAL_RE.match(cleaned):
        return True
    if _NUMBER_LITERAL_RE.match(cleaned):
        return True
    alias_match = _ALIASED_EXPRESSION_RE.match(cleaned)
    if alias_match and is_constant_transform_expression(alias_match.group("expr")):
        return True
    return _RUNTIME_CONSTANT_RE.search(cleaned) is not None


def constant_expression_from_select_item(select_item: str, target_field: str) -> str:
    """Extract a constant expression from a SELECT item like ``NULL AS vendor_code``."""
    cleaned = (select_item or "").strip().rstrip(";").strip()
    field = (target_field or "").strip().strip("`").lower()
    if not cleaned or not field:
        return ""
    alias_re = re.compile(
        rf"^(?P<expr>.+?)\s+(?:as\s+)?`?{re.escape(field)}`?$",
        re.I,
    )
    match = alias_re.match(cleaned)
    expression = match.group("expr").strip() if match else cleaned
    if is_constant_transform_expression(expression):
        return expression.upper() if expression.lower() == "null" else expression
    return ""


def constant_expression_from_reason(reason: str, target_field: str) -> tuple[str, str]:
    """Return ``(expression, evidence_sql)`` when unresolved text describes a constant."""
    for item in _BACKTICK_TEXT_RE.findall(reason or ""):
        expression = constant_expression_from_select_item(item, target_field)
        if expression:
            return expression, item.strip()
    field = (target_field or "").strip().strip("`").lower()
    if field and _NULL_CONSTANT_REASON_RE.search(reason or ""):
        return "NULL", f"NULL AS {field}"
    return "", ""
